export type SourceCatalogEntry = {
  slug: string;
  title: string;
  url: string;
  platform: string;
  sourceType: string;
  availableData: string;
  easyToScrape: boolean;
  needsManualExport: boolean;
  reliabilityScore: number;
  extractionPriority: number;
  notes: string;
  extraction?: {
    mode: "mapstr" | "figaro-article";
    enabled: boolean;
    placeName?: string;
    cuisineType?: string | null;
    foodType?: string[];
    tags?: string[];
    recommendedItems?: string[];
    reasonHint?: string;
  };
};

export const INFLUENCER = {
  name: "Philippine Darblay",
  handle: "philoudarblay",
  city: "Paris",
  country: "France",
  languages: ["French", "English"],
};

export const SOURCE_CATALOG: SourceCatalogEntry[] = [
  {
    slug: "mapstr-public-map",
    title: "Philippine Darblay public Mapstr map",
    url: "https://mapstr.com/map/philoudarblay",
    platform: "mapstr",
    sourceType: "public map",
    availableData:
      "Full public map via embedded web app API: exact place names, addresses, tags, coordinates, websites, booking links, and Mapstr place IDs.",
    easyToScrape: true,
    needsManualExport: false,
    reliabilityScore: 9.8,
    extractionPriority: 1,
    notes:
      "Fastest high-signal source. The HTML page only exposes a 100-place JSON-LD preview, but the embedded public web app exposes the full map payload.",
    extraction: {
      mode: "mapstr",
      enabled: true,
      tags: ["mapstr", "public-map"],
    },
  },
  {
    slug: "figaro-dossier",
    title: "Les adresses de Philippine dossier",
    url: "https://madame.lefigaro.fr/celebrites/culture/dossier/les-adresses-de-philippine",
    platform: "madame-figaro",
    sourceType: "editorial hub",
    availableData: "Index of episode URLs with short summaries and recurring series context.",
    easyToScrape: true,
    needsManualExport: false,
    reliabilityScore: 8.6,
    extractionPriority: 2,
    notes: "Best discovery page for finding individual food-focused episodes without touching Instagram.",
  },
  {
    slug: "figaro-27-4",
    title: "Les adresses de Philippine au 27/4 Sushi Yoshinaga",
    url: "https://madame.lefigaro.fr/cuisine/actu-cuisine/en-video-les-adresses-de-philippine-au-27-4-le-nouveau-temple-de-l-art-de-vivre-japonais-a-paris-20231027",
    platform: "madame-figaro",
    sourceType: "article",
    availableData: "Place name, publication date, description, article body, recommendation context.",
    easyToScrape: true,
    needsManualExport: false,
    reliabilityScore: 8.8,
    extractionPriority: 2,
    notes: "Useful for cuisine and dish context even if the exact street address is not exposed on-page.",
    extraction: {
      mode: "figaro-article",
      enabled: true,
      placeName: "27/4 Sushi Yoshinaga",
      cuisineType: "Japanese",
      foodType: ["restaurant"],
      tags: ["madame-figaro", "omakase", "high-end"],
      recommendedItems: ["omakase", "dorade sashimi"],
      reasonHint: "A futuristic sake bar and intimate omakase restaurant in Paris's 2nd arrondissement.",
    },
  },
  {
    slug: "figaro-kape",
    title: "Les adresses de Philippine chez Kapé",
    url: "https://madame.lefigaro.fr/cuisine/actu-cuisine/en-video-les-adresses-de-philippine-chez-kape-le-nouveau-cafe-philippin-a-paris-20240219",
    platform: "madame-figaro",
    sourceType: "article",
    availableData: "Place name, publication date, article body, specific products mentioned.",
    easyToScrape: true,
    needsManualExport: false,
    reliabilityScore: 8.8,
    extractionPriority: 2,
    notes: "Great for recommended-items extraction because the article body names multiple specialties.",
    extraction: {
      mode: "figaro-article",
      enabled: true,
      placeName: "Kapé",
      cuisineType: "Filipino",
      foodType: ["cafe"],
      tags: ["madame-figaro", "coffee", "11e"],
      recommendedItems: ["coffee jelly", "puto", "coconut milk jam"],
      reasonHint: "A Filipino cafe in the 11th arrondissement created to share Philippine culinary culture.",
    },
  },
  {
    slug: "figaro-48-collagen-cafe",
    title: "Les adresses de Philippine au 48 Collagen Café",
    url: "https://madame.lefigaro.fr/cuisine/actu-cuisine/en-video-les-adresses-de-philippine-au-48-collagen-cafe-premier-cafe-dedie-au-collagene-a-paris-20240123",
    platform: "madame-figaro",
    sourceType: "article",
    availableData: "Place name, arrondissement, article body, signature drink mention.",
    easyToScrape: true,
    needsManualExport: false,
    reliabilityScore: 8.4,
    extractionPriority: 3,
    notes: "High review value because the concept and product category are explicit.",
    extraction: {
      mode: "figaro-article",
      enabled: true,
      placeName: "48 Collagen Café",
      cuisineType: null,
      foodType: ["cafe"],
      tags: ["madame-figaro", "wellness", "9e"],
      recommendedItems: ["Yellowstone Latte"],
      reasonHint: "A collagen-focused cafe in the 9th arrondissement with colorful functional drinks.",
    },
  },
  {
    slug: "figaro-donna",
    title: "Les adresses de Philippine au Donna",
    url: "https://madame.lefigaro.fr/cuisine/tendances-culinaires/en-video-les-adresses-de-philippine-au-donna-cave-a-manger-a-deux-pas-du-centre-pompidou-20230926",
    platform: "madame-figaro",
    sourceType: "article",
    availableData: "Place name, article body, concept notes, nearby landmark context.",
    easyToScrape: true,
    needsManualExport: false,
    reliabilityScore: 8.3,
    extractionPriority: 3,
    notes: "Wine bar and restaurant context are explicit; exact address still needs enrichment.",
    extraction: {
      mode: "figaro-article",
      enabled: true,
      placeName: "Donna",
      cuisineType: null,
      foodType: ["bar", "restaurant"],
      tags: ["madame-figaro", "wine-bar", "centre-pompidou"],
      reasonHint: "A cave a manger near Centre Pompidou focused on natural wine and creative seasonal cooking.",
    },
  },
  {
    slug: "figaro-manteigaria",
    title: "Les adresses de Philippine chez Manteigaria",
    url: "https://madame.lefigaro.fr/cuisine/tendances-culinaires/en-video-les-adresses-de-philippine-chez-manteigaria-temple-du-pasteis-de-nata-20231114",
    platform: "madame-figaro",
    sourceType: "article",
    availableData: "Place name, article body, product focus, tasting notes.",
    easyToScrape: true,
    needsManualExport: false,
    reliabilityScore: 8.5,
    extractionPriority: 3,
    notes: "Clear pastry specialization makes it useful for food-type filters.",
    extraction: {
      mode: "figaro-article",
      enabled: true,
      placeName: "Manteigaria",
      cuisineType: "Portuguese",
      foodType: ["bakery", "pastry-shop"],
      tags: ["madame-figaro", "pastry", "pastel-de-nata"],
      recommendedItems: ["pastel de nata"],
      reasonHint: "A Portuguese pastry address centered on pasteis de nata.",
    },
  },
  {
    slug: "figaro-muse",
    title: "Les adresses de Philippine chez Muse",
    url: "https://madame.lefigaro.fr/cuisine/tendances-culinaires/en-video-les-adresses-de-philippine-chez-muse-le-nouveau-restaurant-afro-caribeen-20240408",
    platform: "madame-figaro",
    sourceType: "article",
    availableData: "Place name, article body, cuisine and setting notes.",
    easyToScrape: true,
    needsManualExport: false,
    reliabilityScore: 8.2,
    extractionPriority: 3,
    notes: "Cuisine type is explicit and helpful for browsing.",
    extraction: {
      mode: "figaro-article",
      enabled: true,
      placeName: "Muse",
      cuisineType: "Afro-Caribbean",
      foodType: ["restaurant"],
      tags: ["madame-figaro", "afro-caribbean"],
      reasonHint: "A convivial afro-caribbean restaurant inside a cinema-focused creative venue.",
    },
  },
  {
    slug: "figaro-nepita",
    title: "Les adresses de Philippine chez Nepita",
    url: "https://madame.lefigaro.fr/cuisine/tendances-culinaires/en-video-les-adresses-de-philippine-chez-nepita-le-nouveau-restaurant-aux-inspirations-mediterraneenne-20240611",
    platform: "madame-figaro",
    sourceType: "article",
    availableData: "Place name, neighborhood context, cuisine notes.",
    easyToScrape: true,
    needsManualExport: false,
    reliabilityScore: 8.2,
    extractionPriority: 3,
    notes: "Mediterranean cues and Madeleine location are visible in the article snippet.",
    extraction: {
      mode: "figaro-article",
      enabled: true,
      placeName: "Nepita",
      cuisineType: "Mediterranean",
      foodType: ["restaurant"],
      tags: ["madame-figaro", "madeleine", "hotel-restaurant"],
      reasonHint: "A calm Mediterranean-leaning restaurant tucked inside Hotel Florida near Madeleine.",
    },
  },
  {
    slug: "figaro-cafe-usine",
    title: "Les adresses de Philippine au Café de l’Usine",
    url: "https://madame.lefigaro.fr/cuisine/actu-cuisine/en-video-les-adresses-de-philippine-au-cafe-de-l-usine-pour-decouvrir-la-carte-de-la-cheffe-alice-arnoux-20241206",
    platform: "madame-figaro",
    sourceType: "article",
    availableData: "Place name, arrondissement, article body, recommended dishes.",
    easyToScrape: true,
    needsManualExport: false,
    reliabilityScore: 8.9,
    extractionPriority: 2,
    notes: "One of the richest food-focused articles in the series.",
    extraction: {
      mode: "figaro-article",
      enabled: true,
      placeName: "Café de l’Usine",
      cuisineType: null,
      foodType: ["restaurant"],
      tags: ["madame-figaro", "11e", "chef-driven"],
      recommendedItems: [
        "burnt yellow beet carpaccio",
        "creative tempuras",
        "chawanmushi",
      ],
      reasonHint: "Alice Arnoux's refined, family-style restaurant in the 11th arrondissement.",
    },
  },
  {
    slug: "figaro-datcha",
    title: "Les adresses de Philippine à La Datcha",
    url: "https://madame.lefigaro.fr/cuisine/actu-cuisine/en-video-les-adresses-de-philippine-a-la-datcha-pour-un-brunch-gourmand-et-raffine-20241204",
    platform: "madame-figaro",
    sourceType: "article",
    availableData: "Place name, arrondissement, brunch angle, article body.",
    easyToScrape: true,
    needsManualExport: false,
    reliabilityScore: 8.5,
    extractionPriority: 2,
    notes: "Good brunch tag source and useful for the 11th arrondissement.",
    extraction: {
      mode: "figaro-article",
      enabled: true,
      placeName: "La Datcha",
      cuisineType: null,
      foodType: ["restaurant", "brunch"],
      tags: ["madame-figaro", "11e", "brunch"],
      reasonHint: "A refined bistronomic brunch address in the 11th arrondissement.",
    },
  },
  {
    slug: "figaro-matka",
    title: "Les adresses de Philippine au restaurant Matka",
    url: "https://madame.lefigaro.fr/cuisine/actu-cuisine/en-video-les-adresses-de-philippine-au-restaurant-matka-20241021",
    platform: "madame-figaro",
    sourceType: "article",
    availableData: "Place name, arrondissement, cuisine notes, article body.",
    easyToScrape: true,
    needsManualExport: false,
    reliabilityScore: 8.6,
    extractionPriority: 2,
    notes: "Cuisine and arrondissement are both explicit in public snippets.",
    extraction: {
      mode: "figaro-article",
      enabled: true,
      placeName: "Matka",
      cuisineType: "Polish",
      foodType: ["restaurant"],
      tags: ["madame-figaro", "3e", "polish"],
      reasonHint: "A Polish restaurant in the 3rd arrondissement described as a small gastronomic gem.",
    },
  },
  {
    slug: "figaro-paul-chene",
    title: "Les adresses de Philippine chez Paul Chêne",
    url: "https://madame.lefigaro.fr/cuisine/actu-cuisine/en-video-les-adresses-de-philippine-chez-paul-chene-pour-deguster-les-meilleures-frites-de-paris-20250430",
    platform: "madame-figaro",
    sourceType: "article",
    availableData: "Place name, dish hook, article context.",
    easyToScrape: true,
    needsManualExport: false,
    reliabilityScore: 8.2,
    extractionPriority: 3,
    notes: "Helpful for dish-tagging and evidence even if some fields still need enrichment.",
    extraction: {
      mode: "figaro-article",
      enabled: true,
      placeName: "Paul Chêne",
      cuisineType: "French",
      foodType: ["restaurant"],
      tags: ["madame-figaro", "frites", "bistro"],
      recommendedItems: ["fries"],
      reasonHint: "A bistro singled out for some of Paris's best fries.",
    },
  },
  {
    slug: "kessel-newsletter-profile",
    title: "Kessel newsletter profile",
    url: "https://www.kessel-media.com/",
    platform: "kessel",
    sourceType: "newsletter landing page",
    availableData: "Confirms newsletter existence and positioning around addresses and portraits.",
    easyToScrape: true,
    needsManualExport: true,
    reliabilityScore: 6.4,
    extractionPriority: 5,
    notes: "Promising future source, but archive access is not obvious from the public landing page.",
  },
  {
    slug: "longchamp-paris-artisan-guide",
    title: "Longchamp Paris Artisan Guide by Philippine Darblay",
    url: "https://www.longchamp.com/ca/en/maison-longchamp/editorials/paris-artisan-guide.html",
    platform: "longchamp",
    sourceType: "brand editorial",
    availableData: "Three exact Paris addresses personally selected by Philippine Darblay.",
    easyToScrape: true,
    needsManualExport: false,
    reliabilityScore: 7.4,
    extractionPriority: 6,
    notes: "High-confidence editorial source, but these picks are artisanal addresses rather than food-only places.",
  },
];

export const EXTRACTABLE_SOURCES = SOURCE_CATALOG.filter(
  (entry) => entry.extraction?.enabled,
);
